function generateRuntimeEnvLines(
	clientKeys: string[],
	sharedKeys: string[],
): string {
	const allKeys = Array.from(new Set([...clientKeys, ...sharedKeys]));
	return allKeys.map((key) => `\t\t\t${key}: process.env.${key},`).join("\n");
}

const GENERATED_HEADER = `/* eslint-disable */
// biome-ignore format: auto-generated
// Generated by ArkEnv. DO NOT EDIT DIRECTLY.
`;

const GENERATED_FOOTER = `
export default arkenv;
`;

/**
 * Generate the flat `@/.arkenv` factory module for Next.js codegen.
 *
 * @param clientKeys Keys exposed via the `NEXT_PUBLIC_` prefix
 * @param sharedKeys Keys listed in `exposeToClient` (plus `NODE_ENV`)
 * @param isStandard Whether to generate the Standard Schema factory
 * @returns The generated factory TypeScript source
 */
export function generateFlatFactoryCode(
	clientKeys: string[],
	sharedKeys: string[],
	isStandard?: boolean,
): string {
	const runtimeEnvLines = generateRuntimeEnvLines(clientKeys, sharedKeys);
	const importPath = isStandard ? "@arkenv/nextjs/standard" : "@arkenv/nextjs";
	const coreName = "arkenv";
	const typeImport = isStandard
		? ""
		: '\nimport type { type as at, distill } from "arktype";';
	const returnType = isStandard
		? "Readonly<TSchema>"
		: "Readonly<distill.Out<at.infer<TSchema>>>";
	const castReturn = isStandard
		? ""
		: " as unknown as Readonly<distill.Out<at.infer<TSchema>>>";
	const callPrefix = "coreArkenv";

	return `${GENERATED_HEADER}
import { ${coreName} as coreArkenv } from "${importPath}";${typeImport}

export function arkenv<
	const TSchema extends Record<string, unknown> & { runtimeEnv?: never } = {},
	const TExpose extends keyof TSchema = never,
	const TExtends extends readonly unknown[] = [],
>(
	schema: TSchema,
	options?: {
		/**
		 * Custom environment variables to expose to the client bundle.
		 * By default, variables prefixed with \`NEXT_PUBLIC_\` and \`NODE_ENV\` are exposed automatically.
		 * Use this option to expose custom variables that do not have the \`NEXT_PUBLIC_\` prefix.
		 */
		exposeToClient?: readonly TExpose[];
		extends?: [...TExtends];
	},
): ${returnType} {
	const env = ${callPrefix}(schema as any, {
		...options,
		runtimeEnv: {
			${runtimeEnvLines}
		},
	} as any);
	return env${castReturn};
}
${GENERATED_FOOTER}`;
}
