import fs from "node:fs";
import path from "node:path";
import {
	extractClientKeys,
	extractKeys,
	extractServerKeys,
	extractSharedKeys,
	type LayoutMode,
	resolveLayout,
} from "@arkenv/build";

/**
 * Run code generation to read the schema file and generate the env.gen.ts helper.
 *
 * @param schemaPath The absolute path to the schema file or directory
 * @param outputPath The absolute path to the generated output file
 * @param layoutOption The explicit layout configuration option
 */
export function runCodegen(
	schemaPath: string,
	outputPath: string,
	layoutOption?: LayoutMode,
): void {
	const { layout: resolvedLayout, baseDir } = resolveLayout(
		schemaPath,
		layoutOption,
	);

	let generatedCode = "";
	if (resolvedLayout === "strict") {
		const clientPath = path.join(baseDir, "client.ts");
		const sharedPath = path.join(baseDir, "internal", "shared.ts");
		const serverPath = path.join(baseDir, "server.ts");

		const clientContent = fs.existsSync(clientPath)
			? fs.readFileSync(clientPath, "utf-8")
			: "";
		const sharedContent = fs.existsSync(sharedPath)
			? fs.readFileSync(sharedPath, "utf-8")
			: "";
		const serverContent = fs.existsSync(serverPath)
			? fs.readFileSync(serverPath, "utf-8")
			: "";

		const clientKeys = extractClientKeys(clientContent);
		const sharedKeys = extractSharedKeys(sharedContent);
		const serverKeys = extractServerKeys(serverContent);

		generatedCode = generateClientFactoryCode(
			serverKeys,
			clientKeys,
			sharedKeys,
		);
	} else {
		const fileContent = fs.readFileSync(schemaPath, "utf-8");
		const { serverKeys, clientKeys, sharedKeys } = extractKeys(fileContent);
		generatedCode = generateFactoryCode(serverKeys, clientKeys, sharedKeys);
	}

	const outputDir = path.dirname(outputPath);
	if (!fs.existsSync(outputDir)) {
		fs.mkdirSync(outputDir, { recursive: true });
	}

	let shouldWrite = true;
	if (fs.existsSync(outputPath)) {
		const existingContent = fs.readFileSync(outputPath, "utf-8");
		if (existingContent === generatedCode) {
			shouldWrite = false;
		}
	}

	if (shouldWrite) {
		fs.writeFileSync(outputPath, generatedCode, "utf-8");
	}
}

/**
 * Generate the code for the client/server factory file (`env.gen.ts`) in simple layout mode.
 *
 * @param serverKeys The server environment variable keys
 * @param clientKeys The client environment variable keys
 * @param sharedKeys The shared environment variable keys
 * @returns The generated TypeScript code as a string
 */
function generateFactoryCode(
	serverKeys: string[],
	clientKeys: string[],
	sharedKeys: string[],
): string {
	const serverEnvLines = serverKeys
		.map((key) => `\t\t\t\t${key}: config?.${key} ?? process.env.${key},`)
		.join("\n");
	const clientSharedEnvLines = Array.from(
		new Set([...clientKeys, ...sharedKeys]),
	)
		.map((key) => `\t\t\t${key}: config?.public?.${key} ?? process.env.${key},`)
		.join("\n");

	const serverGuard =
		serverKeys.length > 0
			? `\t\t\t...(isServer ? {\n${serverEnvLines}\n\t\t\t} : {}),`
			: "";

	const runtimeEnvLines = [clientSharedEnvLines, serverGuard]
		.filter(Boolean)
		.join("\n");

	return `/* eslint-disable */
// prettier-ignore
// biome-ignore format: auto-generated
/**
 * @file env.gen.ts
 * @note This file is auto-generated by ArkEnv. DO NOT EDIT DIRECTLY.
 * @see https://arkenv.js.org
 */

import { createEnv as coreCreateEnv } from "@arkenv/nuxt";
import type { Infer } from "@arkenv/nuxt";
// @ts-ignore
import { useRuntimeConfig } from "#imports";

export { type } from "@arkenv/nuxt";

function getRuntimeConfig() {
	try {
		return useRuntimeConfig();
	} catch {
		return null;
	}
}

export function createEnv<
	const TServer extends Record<string, any> = {},
	const TClient extends Record<string, any> = {},
	const TShared extends Record<string, any> = {},
>(options: {
	server?: TServer;
	client?: TClient & {
		[K in keyof TClient]: K extends \`NUXT_PUBLIC_\${string}\` ? unknown : never;
	};
	shared?: TShared;
}): Readonly<Infer<TServer & TClient & TShared>> {
	const config = getRuntimeConfig();
	const isServer = typeof window === "undefined";
	return coreCreateEnv({
		...options,
		server: isServer ? options.server : undefined,
		runtimeEnv: {
${runtimeEnvLines}
		},
	} as any) as any;
}

const arkenv = createEnv;
export default arkenv;
`;
}

/**
 * Generate the code for the client-side factory file (`env.gen.ts`) in strict layout mode.
 *
 * @param serverKeys The server environment variable keys
 * @param clientKeys The client environment variable keys
 * @param sharedKeys The shared environment variable keys
 * @returns The generated TypeScript code as a string
 */
function generateClientFactoryCode(
	serverKeys: string[],
	clientKeys: string[],
	sharedKeys: string[],
): string {
	const clientSharedEnvLines = Array.from(
		new Set([...clientKeys, ...sharedKeys]),
	)
		.map((key) => `\t\t\t${key}: config?.public?.${key} ?? process.env.${key},`)
		.join("\n");

	return `/* eslint-disable */
// prettier-ignore
// biome-ignore format: auto-generated
/**
 * @file env.gen.ts
 * @note This file is auto-generated by ArkEnv. DO NOT EDIT DIRECTLY.
 * @see https://arkenv.js.org
 */

import { createEnv as coreCreateEnv } from "@arkenv/nuxt/client";
// @ts-ignore
import { useRuntimeConfig } from "#imports";

export { type } from "@arkenv/nuxt/client";

function getRuntimeConfig() {
	try {
		return useRuntimeConfig();
	} catch {
		return null;
	}
}

export function createEnv<
	const TSchema extends Record<string, any> = {},
	const TExtends extends readonly unknown[] = [],
>(
	schema: TSchema & {
		[K in keyof TSchema]: K extends \`NUXT_PUBLIC_\${string}\` ? unknown : never;
	},
	options?: {
		extends?: [...TExtends];
	},
) {
	const config = getRuntimeConfig();
	return coreCreateEnv<TSchema, TExtends>(schema as any, {
		...options,
		runtimeEnv: {
${clientSharedEnvLines}
		},
	} as any);
}

const arkenv = createEnv;
export default arkenv;
`;
}
