# Configuration for GitHub PR Labeler
# https://github.com/actions/labeler

arkenv:
  - changed-files:
    - any-glob-to-any-file: 'packages/arkenv/**/*'

"@arkenv/vite-plugin":
  - changed-files:
    - any-glob-to-any-file: 'packages/vite-plugin/**/*'

"@arkenv/bun-plugin":
  - changed-files:
    - any-glob-to-any-file: 'packages/bun-plugin/**/*'

"@arkenv/cli":
  - changed-files:
    - any-glob-to-any-file: 'packages/cli/**/*'

"@arkenv/fumadocs-ui":
  - changed-files:
    - any-glob-to-any-file: 'packages/fumadocs-ui/**/*'

www:
  - changed-files:
    - any-glob-to-any-file: 'apps/www/**/*'

docs:
  - changed-files:
      - any-glob-to-any-file: ['apps/www/content/docs/**/*', '**/*.md']

example:
  - changed-files:
    - any-glob-to-any-file: 'examples/**/*'
    
playground:
  - changed-files:
    - any-glob-to-any-file: 'apps/playgrounds/**/*'

tests:
  - changed-files:
    - any-glob-to-any-file: ['**/*.test.ts', '**/*.test.tsx']

"github actions":
  - changed-files:
    - any-glob-to-any-file: '**/.github/**/*'
