# Configuration for GitHub PR Labeler
# https://github.com/actions/labeler

arkenv:
  - changed-files:
    - any-glob-to-any-file: 'packages/arkenv/**/*'

"@arkenv/vite-plugin":
  - changed-files:
    - any-glob-to-any-file: 'packages/vite-plugin/**/*'

www:
  - changed-files:
    - any-glob-to-any-file: 'apps/www/**/*'

docs:
  - changed-files:
      - any-glob-to-any-file: ['apps/www/content/docs/**/*', '**/*.md']

example:
  - changed-files:
    - any-glob-to-any-file: 'examples/**/*'

tests:
  - changed-files:
    - any-glob-to-any-file: ['**/*.test.ts', '**/*.test.tsx']
