packages:
  - 'packages/*'
  - 'apps/*'
  - 'apps/playgrounds/*'
  - '!apps/playgrounds/bun'
  - '!apps/playgrounds/bun-react'
  - 'tooling/*'
overrides:
  "@playwright/test": "1.56.1"
  "import-in-the-middle": "2.0.0"
  "require-in-the-middle": "8.0.1"
