packages:
  - packages/*
  - packages/internal/*
  - apps/*
  - apps/playgrounds/*
  - tooling/*

catalog:
  '@axe-core/playwright': 4.11.0
  '@size-limit/esbuild-why': 12.0.0
  '@size-limit/preset-small-lib': 12.0.0
  '@types/bun': 1.3.6
  '@types/node': 24.10.8
  '@types/react': 19.2.8
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react': 5.1.2
  '@vitest/ui': 4.0.17
  arktype: 2.1.29
  bun: 1.3.6
  concurrently: 9.2.1
  globals: 16.5.0
  react: 19.2.3
  react-dom: 19.2.3
  rimraf: 6.1.2
  size-limit: 12.0.0
  tsdown: 0.18.4
  tsx: 4.21.0
  typescript: 5.9.3
  valibot: 1.2.0
  vite-tsconfig-paths: 6.0.4
  vitest: 4.0.17
  zod: 4.3.5

overrides:
  '@playwright/test': 1.57.0
  import-in-the-middle: 2.0.0
  require-in-the-middle: 8.0.1
