packages:
  - 'packages/*'
  - 'apps/*'
  - 'apps/playgrounds/*'
  - '!apps/playgrounds/bun'
  - '!apps/playgrounds/bun-react'
  - 'tooling/*'
overrides:
  "import-in-the-middle": "2.0.0"
  "require-in-the-middle": "8.0.1"
catalog:
  "@playwright/test": "1.56.0"
