/// <reference types="vite/client" />

// Generated by @arkenv/vite-plugin
declare interface ImportMetaEnv {
    readonly VITE_TEST: string;
    readonly VITE_API_URL: string;
    readonly VITE_PORT: string;
    readonly VITE_DEBUG: string;
    readonly VITE_NODE_ENV: 'development' | 'production' | 'test';
}