// This file is auto-generated by @arkenv/nextjs/config. Do not edit directly.
import arkenv from "@arkenv/nextjs";
import { client, server, shared } from "./env.config";

export const env = arkenv({
	server,
	client,
	shared,
	runtimeEnv: {
		NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
		NODE_ENV: process.env.NODE_ENV,
	},
});
