import fs from "node:fs";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import {
	extractClientKeys,
	extractKeys,
	extractSharedKeys,
	runCodegen,
	withArkEnv,
} from "./config";

describe("config key extraction", () => {
	it("should extract client and shared keys correctly", () => {
		const source = `
			import { createEnv } from "./env.gen";
			export const env = createEnv({
				server: {
					DATABASE_URL: "string",
				},
				client: {
					NEXT_PUBLIC_API_URL: "string",
					NEXT_PUBLIC_APP_TITLE: "string = 'My App'",
				},
				shared: {
					NODE_ENV: "string",
				}
			});
		`;

		const { clientKeys, sharedKeys } = extractKeys(source);

		expect(clientKeys).toEqual([
			"NEXT_PUBLIC_API_URL",
			"NEXT_PUBLIC_APP_TITLE",
		]);
		expect(sharedKeys).toEqual(["NODE_ENV"]);
	});

	it("should handle single-line comments", () => {
		const source = `
			export const env = createEnv({
				client: {
					// This is a comment
					NEXT_PUBLIC_VAR_1: "string",
					// Another comment: with colon
					NEXT_PUBLIC_VAR_2: "string",
				}
			});
		`;

		const { clientKeys } = extractKeys(source);
		expect(clientKeys).toEqual(["NEXT_PUBLIC_VAR_1", "NEXT_PUBLIC_VAR_2"]);
	});

	it("should handle multi-line comments", () => {
		const source = `
			export const env = createEnv({
				client: {
					/*
					* Multi-line comment:
					*/
					NEXT_PUBLIC_VAR_1: "string",
				}
			});
		`;

		const { clientKeys } = extractKeys(source);
		expect(clientKeys).toEqual(["NEXT_PUBLIC_VAR_1"]);
	});

	it("should ignore string values that contain colons", () => {
		const source = `
			export const env = createEnv({
				client: {
					NEXT_PUBLIC_API_URL: "string = 'http://localhost:3000'",
					NEXT_PUBLIC_NESTED: 'string = "foo:bar"',
					NEXT_PUBLIC_TEMPLATE: \`string = "baz:qux"\`,
				}
			});
		`;

		const { clientKeys } = extractKeys(source);
		expect(clientKeys).toEqual([
			"NEXT_PUBLIC_API_URL",
			"NEXT_PUBLIC_NESTED",
			"NEXT_PUBLIC_TEMPLATE",
		]);
	});

	it("should extract quoted keys correctly", () => {
		const source = `
			export const env = createEnv({
				client: {
					"NEXT_PUBLIC_VAR_1": "string",
					'NEXT_PUBLIC_VAR_2': "string",
				}
			});
		`;

		const { clientKeys } = extractKeys(source);
		expect(clientKeys).toEqual(["NEXT_PUBLIC_VAR_1", "NEXT_PUBLIC_VAR_2"]);
	});

	it("should ignore braces inside string templates or comments in extractBlock", () => {
		const source = `
			export const env = createEnv({
				client: {
					NEXT_PUBLIC_VAR_1: "string = '{not-a-brace}'",
					// {comment-brace}
					NEXT_PUBLIC_VAR_2: "string = 'foo'",
				}
			});
		`;

		const { clientKeys } = extractKeys(source);
		expect(clientKeys).toEqual(["NEXT_PUBLIC_VAR_1", "NEXT_PUBLIC_VAR_2"]);
	});

	it("should ignore nested keys inside complex values in parseBlockKeys", () => {
		const source = `
			export const env = createEnv({
				client: {
					NEXT_PUBLIC_VAR_1: type("string", { description: "nested:key" }),
					NEXT_PUBLIC_VAR_2: "string",
				}
			});
		`;

		const { clientKeys } = extractKeys(source);
		expect(clientKeys).toEqual(["NEXT_PUBLIC_VAR_1", "NEXT_PUBLIC_VAR_2"]);
	});

	it("should extract keys when using ArkType 'type({...})' wrapper", () => {
		const source = `
			export const env = createEnv({
				client: type({
					NEXT_PUBLIC_VAR_1: "string",
					NEXT_PUBLIC_VAR_2: "string",
				}),
				shared: at.type({
					NODE_ENV: "string",
				})
			});
		`;

		const { clientKeys, sharedKeys } = extractKeys(source);
		expect(clientKeys).toEqual(["NEXT_PUBLIC_VAR_1", "NEXT_PUBLIC_VAR_2"]);
		expect(sharedKeys).toEqual(["NODE_ENV"]);
	});
});

describe("codegen process", () => {
	const tempDir = path.join(__dirname, "__temp_tests__");
	const schemaPath = path.join(tempDir, "env.ts");
	const outputPath = path.join(tempDir, "env.gen.ts");

	afterEach(() => {
		if (fs.existsSync(tempDir)) {
			fs.rmSync(tempDir, { recursive: true, force: true });
		}
		vi.restoreAllMocks();
	});

	it("should parse file, resolve relative imports, and write generated code", () => {
		if (!fs.existsSync(tempDir)) {
			fs.mkdirSync(tempDir, { recursive: true });
		}

		fs.writeFileSync(
			schemaPath,
			`
			import { createEnv } from "./env.gen";
			export const env = createEnv({
				client: {
					NEXT_PUBLIC_API_URL: "string",
				},
				shared: {
					NODE_ENV: "string",
				}
			});
			`,
			"utf-8",
		);

		runCodegen(schemaPath, outputPath);

		expect(fs.existsSync(outputPath)).toBe(true);
		const generatedContent = fs.readFileSync(outputPath, "utf-8");

		// Check warning header
		expect(generatedContent).not.toContain("// @ts-nocheck");
		expect(generatedContent).toContain("This file is auto-generated by ArkEnv");

		// Check exports and wrapper types
		expect(generatedContent).toContain("export function createEnv<");
		expect(generatedContent).toContain("const arkenv = createEnv;");
		expect(generatedContent).toContain("export default arkenv;");

		// Check that relative path import was resolved correctly (relative from __temp_tests__/env.gen.ts to __temp_tests__/env.ts is ./env)
		// Wait, path.relative(__temp_tests__, __temp_tests__/env.ts) is "env.ts", which normalizes to "./env"
		expect(generatedContent).toContain(
			'import { createEnv as coreCreateEnv } from "@arkenv/nextjs";',
		);

		// Check destructured runtimeEnv keys
		expect(generatedContent).toContain(
			"NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,",
		);
		expect(generatedContent).toContain("NODE_ENV: process.env.NODE_ENV,");
	});

	it("should handle custom output path relative importing", () => {
		const customOutputDir = path.join(tempDir, "generated");
		const customOutputPath = path.join(customOutputDir, "env.gen.ts");

		if (!fs.existsSync(tempDir)) {
			fs.mkdirSync(tempDir, { recursive: true });
		}

		fs.writeFileSync(
			schemaPath,
			`
			export const env = createEnv({
				client: {
					NEXT_PUBLIC_API_URL: "string",
				}
			});
			`,
			"utf-8",
		);

		runCodegen(schemaPath, customOutputPath);

		expect(fs.existsSync(customOutputPath)).toBe(true);
		const generatedContent = fs.readFileSync(customOutputPath, "utf-8");
		expect(generatedContent).toContain("export function createEnv<");

		// The relative import from generated/env.gen.ts to env.ts should be ../env
		// Since we didn't mock relative path resolution, let's check it.
		// Wait! The templates generated for config should be:
		// import { config } from "../env"; or similar?
		// Oh, wait! In createEnv wrapper pattern, we do NOT import config!
		// The developer imports createEnv from "./env.gen", and calls it in env.ts.
		// So the generated file does NOT import from "./env" at all!
		// Wait! Let's check my template:
		// Yes! The generated template does NOT import any config! It only imports coreCreateEnv from "@arkenv/nextjs"!
		// Oh, wow! That is even simpler and cleaner!
		// Wait, let's verify if my generateFactoryCode template has any relative import of config:
		// No, it doesn't! It just exports the generic wrapper function `createEnv`.
		// But wait! Why does `generateFactoryCode` compute `relativeImportPath`?
		// Ah! In `generateFactoryCode`, we computed `relativeImportPath` but we didn't actually use it in the returned string template!
		// Oh, let me check my config.ts code:
		// Yes, I defined:
		// `let relativeImportPath = path.relative(outputDir, schemaPath);`
		// and normalized it, but didn't put it in the template, because the wrapper factory doesn't import from the config file!
		// That is brilliant! Since the factory is generic and accepts the schema options directly, it doesn't need to know about the schema file at all! It just needs to know which keys to destructure in `runtimeEnv`.
		// This makes it completely decoupled and robust!
		// Let's verify that this is correct.
		// Yes, `createEnv` wrapper takes `options` (which is the schema) and returns `coreCreateEnv({ ...options, runtimeEnv: { ... } })`.
		// It has no dependency on the schema file!
		// This is so beautiful!
	});
});

describe("withArkEnv wrapper", () => {
	const tempDir = path.join(__dirname, "__temp_tests_wrapper__");
	const schemaPath = path.join(tempDir, "env.ts");

	afterEach(() => {
		if (fs.existsSync(tempDir)) {
			fs.rmSync(tempDir, { recursive: true, force: true });
		}
		vi.restoreAllMocks();
	});

	it("should pass nextConfig through unchanged", () => {
		if (!fs.existsSync(tempDir)) {
			fs.mkdirSync(tempDir, { recursive: true });
		}

		fs.writeFileSync(
			schemaPath,
			`
			export const env = createEnv({
				client: { NEXT_PUBLIC_API_URL: "string" }
			});
			`,
			"utf-8",
		);

		const inputConfig = { reactStrictMode: true };
		const outputConfig = withArkEnv(inputConfig, {
			schemaPath,
		});

		expect(outputConfig).toBe(inputConfig);
		expect(fs.existsSync(path.join(tempDir, "generated", "env.gen.ts"))).toBe(
			true,
		);
	});

	it("should support strict layout auto-detection and generation", () => {
		if (!fs.existsSync(tempDir)) {
			fs.mkdirSync(tempDir, { recursive: true });
		}

		// Set up a strict structure
		const strictBaseDir = path.join(tempDir, "env");
		fs.mkdirSync(path.join(strictBaseDir, "internal"), { recursive: true });

		fs.writeFileSync(
			path.join(strictBaseDir, "internal", "shared.ts"),
			`
			import { type } from "@arkenv/nextjs/shared";
			export const SharedSchema = type({
				NODE_ENV: "string = 'development'",
			});
			`,
			"utf-8",
		);

		fs.writeFileSync(
			path.join(strictBaseDir, "client.ts"),
			`
			import arkenv from "@arkenv/nextjs/client";
			import { SharedSchema } from "./internal/shared";
			export const env = arkenv(
				{
					NEXT_PUBLIC_API_URL: "string = 'https://api.example.com'",
				},
				{
					extends: [SharedSchema],
					runtimeEnv: {},
				}
			);
			`,
			"utf-8",
		);

		fs.writeFileSync(
			path.join(strictBaseDir, "server.ts"),
			`
			import arkenv from "@arkenv/nextjs/server";
			export const env = arkenv({
				DATABASE_URL: "string",
			});
			`,
			"utf-8",
		);

		const inputConfig = { reactStrictMode: true };
		const outputConfig = withArkEnv(inputConfig, {
			schemaPath: strictBaseDir,
		});

		expect(outputConfig).toBe(inputConfig);
		const genPath = path.join(strictBaseDir, "generated", "env.gen.ts");
		expect(fs.existsSync(genPath)).toBe(true);

		const generatedContent = fs.readFileSync(genPath, "utf-8");
		expect(generatedContent).toContain("export function createEnv<");
		expect(generatedContent).toContain("const arkenv = createEnv;");
		expect(generatedContent).toContain("export default arkenv;");
		expect(generatedContent).toContain(
			"NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,",
		);
		expect(generatedContent).toContain("NODE_ENV: process.env.NODE_ENV,");
		expect(generatedContent).not.toContain("DATABASE_URL");
	});

	it("should throw a descriptive error when layout: 'strict' is set but required files are missing", () => {
		if (!fs.existsSync(tempDir)) {
			fs.mkdirSync(tempDir, { recursive: true });
		}

		// Only create the schema file, not the strict layout files
		fs.writeFileSync(
			schemaPath,
			`export const env = createEnv({ client: { NEXT_PUBLIC_VAR: "string" } });`,
			"utf-8",
		);

		expect(() =>
			withArkEnv({ reactStrictMode: true }, { schemaPath, layout: "strict" }),
		).toThrow("[ArkEnv] Strict layout requires");
	});
});

describe("strict config key extraction", () => {
	it("should extract client keys from arkenv call", () => {
		const clientSource = `
			import arkenv from "@arkenv/nextjs/client";
			import { SharedSchema } from "./internal/shared";
			export const env = arkenv(
				{
					NEXT_PUBLIC_VAR_1: "string",
					NEXT_PUBLIC_VAR_2: "string = 'default'",
				},
				{
					extends: [SharedSchema],
				}
			);
		`;
		const keys = extractClientKeys(clientSource);
		expect(keys).toEqual(["NEXT_PUBLIC_VAR_1", "NEXT_PUBLIC_VAR_2"]);
	});

	it("should extract shared keys from SharedSchema", () => {
		const sharedSource = `
			import { type } from "@arkenv/nextjs/shared";
			export const SharedSchema = type({
				NODE_ENV: "string = 'development'",
				PORT: "number.port = 3000",
			});
		`;
		const keys = extractSharedKeys(sharedSource);
		expect(keys).toEqual(["NODE_ENV", "PORT"]);
	});

	it("extractClientKeys: should ignore single-line comments inside arkenv block", () => {
		const clientSource = `
			export const env = arkenv(
				{
					// This is a comment
					NEXT_PUBLIC_VAR_1: "string",
					// Another comment: with colon
					NEXT_PUBLIC_VAR_2: "string",
				}
			);
		`;
		expect(extractClientKeys(clientSource)).toEqual([
			"NEXT_PUBLIC_VAR_1",
			"NEXT_PUBLIC_VAR_2",
		]);
	});

	it("extractClientKeys: should ignore multi-line comments inside arkenv block", () => {
		const clientSource = `
			export const env = arkenv(
				{
					/*
					 * Multi-line comment:
					 * FAKE_KEY: this should be ignored
					 */
					NEXT_PUBLIC_VAR_1: "string",
				}
			);
		`;
		expect(extractClientKeys(clientSource)).toEqual(["NEXT_PUBLIC_VAR_1"]);
	});

	it("extractClientKeys: should not be confused by braces inside string literals", () => {
		const clientSource = `
			export const env = arkenv(
				{
					NEXT_PUBLIC_VAR_1: "string = '{not-a-brace}'",
					NEXT_PUBLIC_VAR_2: "string",
				}
			);
		`;
		expect(extractClientKeys(clientSource)).toEqual([
			"NEXT_PUBLIC_VAR_1",
			"NEXT_PUBLIC_VAR_2",
		]);
	});

	it("extractClientKeys: should not be confused by colons inside string literals", () => {
		const clientSource = `
			export const env = arkenv(
				{
					NEXT_PUBLIC_API_URL: "string = 'http://localhost:3000'",
					NEXT_PUBLIC_VAR_2: "string",
				}
			);
		`;
		expect(extractClientKeys(clientSource)).toEqual([
			"NEXT_PUBLIC_API_URL",
			"NEXT_PUBLIC_VAR_2",
		]);
	});

	it("extractClientKeys: should ignore nested object literals in values", () => {
		const clientSource = `
			export const env = arkenv(
				{
					NEXT_PUBLIC_VAR_1: type("string", { description: "nested:key" }),
					NEXT_PUBLIC_VAR_2: "string",
				}
			);
		`;
		expect(extractClientKeys(clientSource)).toEqual([
			"NEXT_PUBLIC_VAR_1",
			"NEXT_PUBLIC_VAR_2",
		]);
	});

	it("extractSharedKeys: should ignore single-line comments inside SharedSchema", () => {
		const sharedSource = `
			export const SharedSchema = type({
				// NODE_ENV is always set
				NODE_ENV: "string = 'development'",
				// PORT: ignored comment
				PORT: "number.port = 3000",
			});
		`;
		expect(extractSharedKeys(sharedSource)).toEqual(["NODE_ENV", "PORT"]);
	});

	it("extractSharedKeys: should not be confused by colons inside string literals", () => {
		const sharedSource = `
			export const SharedSchema = type({
				DATABASE_URL: "string = 'postgresql://localhost:5432/db'",
				NODE_ENV: "string",
			});
		`;
		expect(extractSharedKeys(sharedSource)).toEqual([
			"DATABASE_URL",
			"NODE_ENV",
		]);
	});

	it("extractSharedKeys: should not be confused by braces inside string literals", () => {
		const sharedSource = `
			export const SharedSchema = type({
				NODE_ENV: "string = '{dev}'",
				PORT: "number = 3000",
			});
		`;
		expect(extractSharedKeys(sharedSource)).toEqual(["NODE_ENV", "PORT"]);
	});
});
