import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
	ensureManypkgWorkspace,
	readWorkspaceCatalog,
	readWorkspacePackages,
	renderPnpmWorkspaceYaml,
} from "./ensure-manypkg-workspace.js";

describe("readWorkspacePackages", () => {
	it("reads Nub workspaces.packages", () => {
		expect(
			readWorkspacePackages({
				workspaces: { packages: ["packages/*", "apps/*"] },
			}),
		).toEqual(["packages/*", "apps/*"]);
	});

	it("rejects missing or empty packages", () => {
		expect(() => readWorkspacePackages({})).toThrow(/workspaces\.packages/);
		expect(() => readWorkspacePackages({ workspaces: {} })).toThrow(
			/workspaces\.packages/,
		);
		expect(() =>
			readWorkspacePackages({ workspaces: { packages: [] } }),
		).toThrow(/workspaces\.packages/);
	});
});

describe("readWorkspaceCatalog", () => {
	it("returns empty object when catalog is absent", () => {
		expect(readWorkspaceCatalog({ workspaces: { packages: ["packages/*"] } })).toEqual(
			{},
		);
	});

	it("reads Nub workspaces.catalog", () => {
		expect(
			readWorkspaceCatalog({
				workspaces: {
					packages: ["packages/*"],
					catalog: { typescript: "5.0.0", vitest: "4.1.5" },
				},
			}),
		).toEqual({ typescript: "5.0.0", vitest: "4.1.5" });
	});

	it("rejects non-object or empty-string catalog entries", () => {
		expect(() =>
			readWorkspaceCatalog({ workspaces: { catalog: [] } }),
		).toThrow(/workspaces\.catalog/);
		expect(() =>
			readWorkspaceCatalog({
				workspaces: { catalog: { typescript: "" } },
			}),
		).toThrow(/workspaces\.catalog/);
	});
});

describe("renderPnpmWorkspaceYaml", () => {
	it("emits generated header and package globs", () => {
		const yaml = renderPnpmWorkspaceYaml(["packages/*", "packages/internal/*"]);
		expect(yaml).toContain("GENERATED by scripts/ensure-manypkg-workspace.js");
		expect(yaml).toContain(
			'packages:\n  - "packages/*"\n  - "packages/internal/*"\n',
		);
		expect(yaml).not.toContain("\ncatalog:\n");
	});

	it("emits sorted catalog entries when present", () => {
		const yaml = renderPnpmWorkspaceYaml(["packages/*"], {
			vitest: "4.1.5",
			typescript: "5.0.0",
		});
		expect(yaml).toContain(
			'catalog:\n  "typescript": "5.0.0"\n  "vitest": "4.1.5"\n',
		);
	});
});

describe("ensureManypkgWorkspace", () => {
	it("writes pnpm-workspace.yaml from package.json SoT", () => {
		const root = mkdtempSync(join(tmpdir(), "ensure-manypkg-"));
		writeFileSync(
			join(root, "package.json"),
			JSON.stringify({
				name: "tmp",
				workspaces: {
					packages: ["packages/*", "apps/*"],
					catalog: { typescript: "5.0.0" },
				},
			}),
		);
		mkdirSync(join(root, "packages"), { recursive: true });

		const first = ensureManypkgWorkspace({ rootDir: root });
		expect(first.changed).toBe(true);
		expect(first.catalog).toEqual({ typescript: "5.0.0" });
		expect(readFileSync(first.path, "utf8")).toBe(first.content);
		expect(first.content).toContain('"typescript": "5.0.0"');

		const second = ensureManypkgWorkspace({ rootDir: root });
		expect(second.changed).toBe(false);

		writeFileSync(
			join(root, "package.json"),
			JSON.stringify({
				name: "tmp",
				workspaces: { packages: ["packages/*"] },
			}),
		);
		const third = ensureManypkgWorkspace({ rootDir: root });
		expect(third.changed).toBe(true);
		expect(third.content).toContain('  - "packages/*"\n');
		expect(third.content).not.toContain("apps/*");
		expect(third.content).not.toContain("\ncatalog:\n");
	});

	it("--check path via write:false reports stale without writing", () => {
		const root = mkdtempSync(join(tmpdir(), "ensure-manypkg-check-"));
		writeFileSync(
			join(root, "package.json"),
			JSON.stringify({
				workspaces: { packages: ["packages/*"] },
			}),
		);
		const result = ensureManypkgWorkspace({ rootDir: root, write: false });
		expect(result.changed).toBe(true);
		expect(() => readFileSync(result.path, "utf8")).toThrow();
	});
});
