import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
	ensureManypkgWorkspace,
	readWorkspacePackages,
	renderPnpmWorkspaceYaml,
} from "./ensure-manypkg-workspace.js";

describe("readWorkspacePackages", () => {
	it("reads Nub workspaces.packages", () => {
		expect(
			readWorkspacePackages({
				workspaces: { packages: ["packages/*", "apps/*"] },
			}),
		).toEqual(["packages/*", "apps/*"]);
	});

	it("rejects missing or empty packages", () => {
		expect(() => readWorkspacePackages({})).toThrow(/workspaces\.packages/);
		expect(() => readWorkspacePackages({ workspaces: {} })).toThrow(
			/workspaces\.packages/,
		);
		expect(() =>
			readWorkspacePackages({ workspaces: { packages: [] } }),
		).toThrow(/workspaces\.packages/);
	});
});

describe("renderPnpmWorkspaceYaml", () => {
	it("emits generated header and package globs", () => {
		const yaml = renderPnpmWorkspaceYaml(["packages/*", "packages/internal/*"]);
		expect(yaml).toContain("GENERATED by scripts/ensure-manypkg-workspace.js");
		expect(yaml).toContain(
			"packages:\n  - packages/*\n  - packages/internal/*\n",
		);
	});
});

describe("ensureManypkgWorkspace", () => {
	it("writes pnpm-workspace.yaml from package.json SoT", () => {
		const root = mkdtempSync(join(tmpdir(), "ensure-manypkg-"));
		writeFileSync(
			join(root, "package.json"),
			JSON.stringify({
				name: "tmp",
				workspaces: {
					packages: ["packages/*", "apps/*"],
				},
			}),
		);
		mkdirSync(join(root, "packages"), { recursive: true });

		const first = ensureManypkgWorkspace({ rootDir: root });
		expect(first.changed).toBe(true);
		expect(readFileSync(first.path, "utf8")).toBe(first.content);

		const second = ensureManypkgWorkspace({ rootDir: root });
		expect(second.changed).toBe(false);

		writeFileSync(
			join(root, "package.json"),
			JSON.stringify({
				name: "tmp",
				workspaces: { packages: ["packages/*"] },
			}),
		);
		const third = ensureManypkgWorkspace({ rootDir: root });
		expect(third.changed).toBe(true);
		expect(third.content).toContain("  - packages/*\n");
		expect(third.content).not.toContain("apps/*");
	});

	it("--check path via write:false reports stale without writing", () => {
		const root = mkdtempSync(join(tmpdir(), "ensure-manypkg-check-"));
		writeFileSync(
			join(root, "package.json"),
			JSON.stringify({
				workspaces: { packages: ["packages/*"] },
			}),
		);
		const result = ensureManypkgWorkspace({ rootDir: root, write: false });
		expect(result.changed).toBe(true);
		expect(() => readFileSync(result.path, "utf8")).toThrow();
	});
});
